### ISSUE TITLE
Phase 1: UI - Adapt Instruction Text Blocks

### ISSUE THREAD

**Issue by jfr609** [jfr609/architecture-refactoring-helper#42]
Currently, for all tabs in phase 1 the instructing text block is the same: "In this section, scenarios can be created based on the ATAM method ...". The should be changed as suggested below

Project Description

In this section, details of a new Microservices migration project are specified. The System Specification, System Description and System Properties fields characterizes the system to be migrated and reflect it's current state. The free-text fields within System Description allow to briefly summarize it's purpose, main functionality and attach additional design diagrams.

Strategic Goals

In this section, the overarching strategic goals of the migration project are collected. These goals provide the foundation for deriving quality attributes of the system to improve in the next step. Each set of goals can combine either several Business/Comany objectives, Organizational objectives, or Process objectives. Each set of goals should be tagged with the used method for elicitation (e.g. Architecture Review), its ownership (e.g. Architect) and involved stakeholders/participants.

Quality Attributes

In this section, several scenarios can be specified that reflect the system's use cases and behaviour from a user perspective. Such scenarios are elicitated e.g. as described in the [ATAM method](https://resources.sei.cmu.edu/library/asset-view.cfm?assetID=5177), typically in the course of an Architecture Review session. 
To each scenario, a set of related quality attributes (to be improved) can be assigned. Furthermore, each scenario is assiged an Importance and Difficulty value ranging from A to C. Importance indicates the relevance of the scenario for the functionality of the entire system, where A means 'important', B means 'medium' and C means 'less important'. Difficulty indicates how much effort is needed (how difficult is) to implement the scenario, where means 'very difficult', B means 'normal' and C means 'easy'.

Scenario Assessment

In his section, all previosly entered scenarios are presented again. In this step, the system architecture styles for implementing each scenario is specified. In the tree, all scenarios can be browsed/selected. For each scenario, the possible architectural style for its implementation shoud be specified - either Monolith, Microservices, Other, or a commbination of them.
To narrow down this selection, the most suitable/preferred architectural style should be picked, which is either Monolith, Microservices, or Other.

Summary

This overview summarizes the specified scenarios regarding the architectural styles that can be used for their implementation (upper chart). As well, it summarizes the scenarios regarding their preferred architectural syle (lower chart). This summary, based on strategic goals, scenarios and related quality attributes provides the basis for a grounded decision for or against migrating the system towards a Microservices architecture.

**Comment by Percaimond** [comment]
Eingefügt in die Phasenfenster
