### ISSUE TITLE
Phase 1: UI - Project Description Design

### ISSUE THREAD

**Issue by jfr609** [jfr609/architecture-refactoring-helper#43]
This issue collects a few design changes/improvements of the tab "Project Description".

1) There is only one Project Description per project - so the "+" to add more than one can be removed. 
![grafik](https://github.com/jfr609/architecture-refactoring-helper/assets/19591662/49c037a5-d3e0-4682-8346-4a0bc34a4213)

2) Rename "System specs" -> "System Specification"
    Rename "Properties" -> "System Properties"
    Rename "System Size" -> "System Size (LOC)"
    Rename "Creationdate" -> "Creation Date"
    Rename "Hosting" -> "Hosting Model"
    Rename "Teams" -> "Number of Teams"
    Rename "Devlopers" -> "Number of Developers"
    Rename "Persistence" -> "Data Persistence"

3) All three columns should start at the top (shift second and third up to the top).
![grafik](https://github.com/jfr609/architecture-refactoring-helper/assets/19591662/04ac4e9f-4321-40ec-8ad1-c4830a4ec10d)

4) "Architecture Patterns" and "Languages" should be a multi-select control so that more than one options can be selected (see UI sketch):
![grafik](https://github.com/jfr609/architecture-refactoring-helper/assets/19591662/b4955cf2-bb4c-4946-b11f-9c22806dc6f8)
"Data Persistence" can remain free-text.

**Comment by Percaimond** [comment]
43.1/2/3 implementiert 43.4 muss noch Put request angepasst werden.
