### ISSUE TITLE
Phase 1: UI - Strategic Goals Design 

### ISSUE THREAD

**Issue by jfr609** [jfr609/architecture-refactoring-helper#44]
This issue collects a few design changes/improvements of the step"Strategic Goals".

1) These three fields are the same for all business goals - so they need to be collected just once, not for every new goal/objective.
![grafik](https://github.com/jfr609/architecture-refactoring-helper/assets/19591662/2e804622-9a8d-4baa-98f4-ca354ca7e4df)

2) Each new objective is either a "Business/Company Objective" or an "Organizational Objective" or a "Process Objective. Perhaps this could be chosen via a drop down box (select 1 out of 3).
The objective itself is a free-text (just as it is now). Each objective (regardless of the type) should get a visible ID like "Obj1", "Obj2", etc. which could be shown in front of the text-field.
![grafik](https://github.com/jfr609/architecture-refactoring-helper/assets/19591662/4c0a539b-5544-4ec6-ae89-8ca6e8f510eb)

**Comment by Percaimond** [comment]
Completed
